//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelInfo.WS_GISServerData {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_GISServerData.GisDataWebServiceSoap")]
    public interface GisDataWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_FindChainInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_FindChainInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_FindChainInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_FindChainInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_FindMileageInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_FindMileageInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_FindMileageInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_FindMileageInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_FindProjectInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_FindProjectInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_FindProjectInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_FindProjectInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_FindDWProjectInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ws_FindDWProjectInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ws_FindDWProjectInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ws_FindDWProjectInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GisDataWebServiceSoapChannel : ModelInfo.WS_GISServerData.GisDataWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GisDataWebServiceSoapClient : System.ServiceModel.ClientBase<ModelInfo.WS_GISServerData.GisDataWebServiceSoap>, ModelInfo.WS_GISServerData.GisDataWebServiceSoap {
        
        public GisDataWebServiceSoapClient() {
        }
        
        public GisDataWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GisDataWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GisDataWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GisDataWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ws_FindChainInfo() {
            return base.Channel.ws_FindChainInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_FindChainInfoAsync() {
            return base.Channel.ws_FindChainInfoAsync();
        }
        
        public System.Data.DataTable ws_FindMileageInfo() {
            return base.Channel.ws_FindMileageInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_FindMileageInfoAsync() {
            return base.Channel.ws_FindMileageInfoAsync();
        }
        
        public System.Data.DataTable ws_FindProjectInfo() {
            return base.Channel.ws_FindProjectInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_FindProjectInfoAsync() {
            return base.Channel.ws_FindProjectInfoAsync();
        }
        
        public System.Data.DataTable ws_FindDWProjectInfo() {
            return base.Channel.ws_FindDWProjectInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ws_FindDWProjectInfoAsync() {
            return base.Channel.ws_FindDWProjectInfoAsync();
        }
    }
}
