//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayGIS.UsrLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsrLogin.UsrLoginSoap")]
    public interface UsrLoginSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUsrLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckUsrLogin(string usracc, string usrpwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUsrLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckUsrLoginAsync(string usracc, string usrpwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUsrLoginEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UsrInfo))]
        RailwayGIS.UsrLogin.ResponseVO CheckUsrLoginEx(string usracc, string usrpwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUsrLoginEx", ReplyAction="*")]
        System.Threading.Tasks.Task<RailwayGIS.UsrLogin.ResponseVO> CheckUsrLoginExAsync(string usracc, string usrpwd);
        
        // CODEGEN: 消息 HelloWorldRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UsrInfo))]
        RailwayGIS.UsrLogin.HelloWorldResponse HelloWorld(RailwayGIS.UsrLogin.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<RailwayGIS.UsrLogin.HelloWorldResponse> HelloWorldAsync(RailwayGIS.UsrLogin.HelloWorldRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private object dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MySoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIDField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsrInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int usrIdField;
        
        private string usrNameField;
        
        private string usrName_EN_USField;
        
        private int firmIdField;
        
        private string firmNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UsrId {
            get {
                return this.usrIdField;
            }
            set {
                this.usrIdField = value;
                this.RaisePropertyChanged("UsrId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UsrName {
            get {
                return this.usrNameField;
            }
            set {
                this.usrNameField = value;
                this.RaisePropertyChanged("UsrName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UsrName_EN_US {
            get {
                return this.usrName_EN_USField;
            }
            set {
                this.usrName_EN_USField = value;
                this.RaisePropertyChanged("UsrName_EN_US");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int FirmId {
            get {
                return this.firmIdField;
            }
            set {
                this.firmIdField = value;
                this.RaisePropertyChanged("FirmId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FirmName {
            get {
                return this.firmNameField;
            }
            set {
                this.firmNameField = value;
                this.RaisePropertyChanged("FirmName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RailwayGIS.UsrLogin.MySoapHeader MySoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string contents;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(RailwayGIS.UsrLogin.MySoapHeader MySoapHeader, string contents) {
            this.MySoapHeader = MySoapHeader;
            this.contents = contents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsrLoginSoapChannel : RailwayGIS.UsrLogin.UsrLoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsrLoginSoapClient : System.ServiceModel.ClientBase<RailwayGIS.UsrLogin.UsrLoginSoap>, RailwayGIS.UsrLogin.UsrLoginSoap {
        
        public UsrLoginSoapClient() {
        }
        
        public UsrLoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsrLoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsrLoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsrLoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckUsrLogin(string usracc, string usrpwd) {
            return base.Channel.CheckUsrLogin(usracc, usrpwd);
        }
        
        public System.Threading.Tasks.Task<string> CheckUsrLoginAsync(string usracc, string usrpwd) {
            return base.Channel.CheckUsrLoginAsync(usracc, usrpwd);
        }
        
        public RailwayGIS.UsrLogin.ResponseVO CheckUsrLoginEx(string usracc, string usrpwd) {
            return base.Channel.CheckUsrLoginEx(usracc, usrpwd);
        }
        
        public System.Threading.Tasks.Task<RailwayGIS.UsrLogin.ResponseVO> CheckUsrLoginExAsync(string usracc, string usrpwd) {
            return base.Channel.CheckUsrLoginExAsync(usracc, usrpwd);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RailwayGIS.UsrLogin.HelloWorldResponse RailwayGIS.UsrLogin.UsrLoginSoap.HelloWorld(RailwayGIS.UsrLogin.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(RailwayGIS.UsrLogin.MySoapHeader MySoapHeader, string contents) {
            RailwayGIS.UsrLogin.HelloWorldRequest inValue = new RailwayGIS.UsrLogin.HelloWorldRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.contents = contents;
            RailwayGIS.UsrLogin.HelloWorldResponse retVal = ((RailwayGIS.UsrLogin.UsrLoginSoap)(this)).HelloWorld(inValue);
            return retVal.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RailwayGIS.UsrLogin.HelloWorldResponse> RailwayGIS.UsrLogin.UsrLoginSoap.HelloWorldAsync(RailwayGIS.UsrLogin.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<RailwayGIS.UsrLogin.HelloWorldResponse> HelloWorldAsync(RailwayGIS.UsrLogin.MySoapHeader MySoapHeader, string contents) {
            RailwayGIS.UsrLogin.HelloWorldRequest inValue = new RailwayGIS.UsrLogin.HelloWorldRequest();
            inValue.MySoapHeader = MySoapHeader;
            inValue.contents = contents;
            return ((RailwayGIS.UsrLogin.UsrLoginSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
